### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by Wu-tn** [tswsxk/TKT#2]
when running the CLI:
python3 DKT.py train \$data_dir/train.json \$data_dir/test.json --hyper_params "nettype=EmbedDKT;ku_num=int(835);hidden_num=int(900);dropout=float(0.5)" --ctx="cuda:0" --model_name DKT --root=$HOME/TKT --root_data_dir=\$root/data/ktbd/\$dataset --data_dir=\$root_data_dir --dataset=junyi

there are some problems that :
Traceback (most recent call last):
  File "DKT.py", line 398, in <module>
    DKT.run()
  File "DKT.py", line 394, in run
    eval("%s.%s" % (DKT.__name__, subcommand))(**cfg_kwargs)
  File "DKT.py", line 329, in train
    module = DKT(cfg=cfg, **kwargs)
  File "DKT.py", line 38, in __init__
    net = self.mod.sym_gen(
  File "/root/github_project/TKT/TKT/DKT/Module/sym/net.py", line 18, in get_net
    return DKTNet(ku_num, hidden_num, nettype, dropout, **kwargs)
  File "/root/github_project/TKT/TKT/DKT/Module/sym/net.py", line 35, in __init__
    nn.Embedding(ku_num * 2, kwargs["latent_dim"]),
KeyError: 'latent_dim'

**Comment by tswsxk** [comment]
The problem has been fixed for we have upgraded the whole architecture. Take a look at the examples folder.
